// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saitynas.Models;

namespace Saitynas.Migrations
{
    [DbContext(typeof(SaitynasContext))]
    [Migration("20191210175800_AddOtherKeys")]
    partial class AddOtherKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Saitynas.Models.TblArtwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ArtworkID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtworkCreatorId")
                        .HasColumnName("ArtworkCreatorID")
                        .HasColumnType("int");

                    b.Property<int>("ArtworkOwnerId")
                        .HasColumnName("ArtworkOwnerID")
                        .HasColumnType("int");

                    b.Property<string>("ArtworkUrl")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ArtworkId")
                        .HasName("PK__tblArtwo__D073AEBB085C0584");

                    b.HasIndex("CreatorId");

                    b.HasIndex("UserId");

                    b.ToTable("tblArtwork");
                });

            modelBuilder.Entity("Saitynas.Models.TblCities", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CityID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CityId")
                        .HasName("PK__tblCitie__F2D21A966B9021CB");

                    b.ToTable("tblCities");
                });

            modelBuilder.Entity("Saitynas.Models.TblCreator", b =>
                {
                    b.Property<int>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreatorID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Pseudonym")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CreatorId")
                        .HasName("PK__tblCreat__6C7548116A821B5A");

                    b.ToTable("tblCreator");
                });

            modelBuilder.Entity("Saitynas.Models.TblRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RatingID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RatingCreatorId")
                        .HasColumnName("RatingCreatorID")
                        .HasColumnType("int");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.Property<int?>("TblCreator")
                        .HasColumnType("int");

                    b.HasKey("RatingId")
                        .HasName("PK__tblRatin__FCCDF85CDB172B29");

                    b.HasIndex("TblCreator");

                    b.ToTable("tblRating");
                });

            modelBuilder.Entity("Saitynas.Models.TblUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__tblUser__1788CCACDC8E890D");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("Saitynas.Models.TblArtwork", b =>
                {
                    b.HasOne("Saitynas.Models.TblCreator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("Saitynas.Models.TblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Saitynas.Models.TblRating", b =>
                {
                    b.HasOne("Saitynas.Models.TblCreator", "Creator")
                        .WithMany()
                        .HasForeignKey("TblCreator");
                });
#pragma warning restore 612, 618
        }
    }
}
